version: '2'

services:
  
  haraka-app:
    image: tiredofit/haraka
    container_name: haraka-app
    volumes:
    - ./data:/data
    - ./certs:/certs
    - ./logs:/var/log
    environment:

    - ZABBIX_HOSTNAME=haraka-app
    - HOSTNAME=mail.example.com

    - ACCEPT_DOMAINS=example.com example2.com
    - REDIS_HOST=haraka-redis

    networks:
      - proxy-tier
    restart: always

  haraka-redis:
    image: tiredofit/redis
    container_name: haraka-redis
    environment:
      - ZABBIX_HOSTNAME=haraka-redis
    volumes:
      - ./redis:/data
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy

